### ISSUE TITLE
No "end" method

### ISSUE THREAD

**Issue by laurence-myers** [andywhite37/redhawk#3]
Docs mention "end()" which doesn't exist. Looks like it's called "thenv()". (Maybe same with "catchesEnd" / "catchesv" and "finallyEnd" / "finallyv")

**Comment by ghost** [comment]
Thanks, yeah, I was just re-reading the docs, and I think they have gotten a little out of sync...  I will look into this.

**Comment by ghost** [comment]
I think the docs are up-to-date now.
